### ISSUE TITLE
Cloudinary Storage

### ISSUE THREAD

**Issue by te9arala9a** [sambecker/exif-photo-blog#10]
Is there any chance to change the blob storage to Cloudinary?

**Comment by EmilianoGarciaLopez** [comment]
The issue with Vercel blob storage is that, on the free plan, it does not have a sufficiently large quota to make it a viable candidate for an image database. I reached the quota within a few hours of uploading just ~7 high resolution photos - from analytics there were only 15 unique visitors

Previously, I've been using the [Vercel image gallery template](https://vercel.com/templates/next.js/image-gallery-starter), which uses cloudinary - the combination of a more generous free tier from cloudinary, as well as built in compression makes it a much more suitable candidate

The exif data would still need to be extracted before uploading to cloudinary, since they paywall the ability to query metadata.

Given that this is such a major migration, it is not reasonable to expect you to rewrite this template with that in mind, but I thought I would explain the reasoning that @te9arala9a might have

**Comment by te9arala9a** [comment]
> No plans to do that currently. What's the use case you have in mind? Just using them as a blob store (like S3), or some other image-related functionality?

More of a free-tier limitation. I understand. I'll try to figure it out on my own. Thanks for the wonderful project.

**Comment by te9arala9a** [comment]
> The issue with Vercel blob storage is that, on the free plan, it does not have a sufficiently large quota to make it a viable candidate for an image database. I reached the quota within a few hours of uploading just ~7 high resolution photos - from analytics there were only 15 unique visitors
> 
> Previously, I've been using the [Vercel image gallery template](https://vercel.com/templates/next.js/image-gallery-starter), which uses cloudinary - the combination of a more generous free tier from cloudinary, as well as built in compression makes it a much more suitable candidate
> 
> The exif data would still need to be extracted before uploading to cloudinary, since they paywall the ability to query metadata.
> 
> Given that this is such a major migration, it is not reasonable to expect you to rewrite this template with that in mind, but I thought I would explain the reasoning that @te9arala9a might have

You pointed out my reasoning extremely well. Thank you.
